var PROFILE={first_name:"",last_name:"",email:"",phone:"",linkedin:"",website:"",github:"",street_address:"",city:"",state:"",zip_code:"",university:"",uni_city:"",gpa:4,major:"",degree:"",uni_start_month:8,uni_start_year:"2017",grad_month:9,grad_year:"2021",degree_received:1,employer1:"",job_title1:"",current_job1:0,job_location1:"",job_start_month1:8,job_start_year1:"",job_end_month1:3,job_end_year1:"",job_desc1:"",employer2:"",job_title2:"",current_job2:1,job_location2:"",job_start_month2:3,job_start_year2:"",
job_end_month2:4,job_end_year2:"",job_desc2:"",employer3:"",job_title3:"",current_job3:1,job_location3:"",job_start_month3:3,job_start_year3:"",job_end_month3:4,job_end_year3:"",job_desc3:"",username:"",password:"",question:"bagool",answer:"bafool"};
const FormPersistence=function(){function q(a,b){b=Object.assign({},{include:[],exclude:[],includeFilter:null,excludeFilter:null},b);let c={};for(let d of a.elements){a=d.tagName;var f=d.type;if(!(f=a==="INPUT"&&f==="file")&&!(f=p(d.name,b.include,b.exclude))){f=d;var h=b.includeFilter,g=b.excludeFilter;f=g&&g(f)||h&&!h(f)?!0:!1}if(!f)if(a==="INPUT")a=d.type,a==="radio"?d.checked&&l(c,d.name,d.value):a==="checkbox"?l(c,d.name,d.checked):l(c,d.name,d.value);else if(a==="TEXTAREA")l(c,d.name,d.value);
else if(a==="SELECT")if(d.multiple)for(let k of d.options)k.selected&&l(c,d.name,k.value);else l(c,d.name,d.value)}return c}function l(a,b,c){b in a||(a[b]=[]);a[b].push(c)}function p(a,b,c){return!a||c.includes(a)||b.length>0&&!b.includes(a)?!0:!1}function e(a,b){b=Object.assign({},{uuid:null,useSessionStorage:!1},b);let c=q(a,b);(b.useSessionStorage?sessionStorage:localStorage).setItem(r(a,b.uuid),JSON.stringify(c))}function m(a,b,c){let f=Object.assign({},{valueFunctions:null,include:[],exclude:[],
includeFilter:null,excludeFilter:null},c);c=[];f.valueFunctions!==null&&(c=w(b,a,f));for(let h in b)p(h,f.include,f.exclude)||c.includes(h)||[...a.elements].filter(g=>{var d;if(d=g.name===h){d=f.includeFilter;var k=f.excludeFilter;d=!(k&&k(g)||d&&!d(g))}return d}).forEach((g,d)=>{var k=b[h],n=g.tagName;if(n==="INPUT")n=g.type,n==="radio"?g.checked=g.value===k[0]:n==="checkbox"?g.checked=k[d]:g.value=k[d];else if(n==="TEXTAREA")g.value=k[d];else if(n==="SELECT")if(g.multiple)for(let t of g.options)t.selected=
k.includes(t.value);else g.value=k[d]})}function u(a,b){var c=Object.assign({},{uuid:null,useSessionStorage:!1},b);if(c=(c.useSessionStorage?sessionStorage:localStorage).getItem(r(a,c.uuid)))c=JSON.parse(c),m(a,c,b)}function v(a,b){b=Object.assign({},{uuid:null,useSessionStorage:!1},b);(b.useSessionStorage?sessionStorage:localStorage).removeItem(r(a,b.uuid))}function w(a,b,c){let f=[];for(let h in c.valueFunctions)if(h in a&&!p(h,c.include,c.exclude)){for(let g of a[h])c.valueFunctions[h](b,g);f.push(h)}return f}
function r(a,b){if(!b&&!a.id)throw Error("form persistence requires a form id or uuid");return"form#"+(b?b:a.id)}return{persist:function(a,b){let c=Object.assign({},{saveOnSubmit:!1},b);u(a,c);let f=()=>e(a,c),h=()=>{window.removeEventListener("unload",f);e(a,c)};window.addEventListener("beforeunload",h);window.addEventListener("unload",f);c.saveOnSubmit||a.addEventListener("submit",()=>{window.removeEventListener("beforeunload",h);window.removeEventListener("unload",f);v(a,c)})},load:u,save:e,clearStorage:v,
serialize:q,deserialize:m}}();(function(){typeof module!=="undefined"&&module.exports&&(module.exports=exports=FormPersistence)})();
window.addEventListener("load",function(){function q(){PROFILE.first_name=document.getElementById("fname").value;PROFILE.last_name=document.getElementById("lname").value;PROFILE.email=document.getElementById("email").value;PROFILE.phone=document.getElementById("phone").value;PROFILE.linkedin=document.getElementById("linkedin").value;PROFILE.website=document.getElementById("website").value;PROFILE.github=document.getElementById("github").value;PROFILE.street_address=document.getElementById("street_address").value;
PROFILE.city=document.getElementById("city").value;PROFILE.state=document.getElementById("selectstate").value;PROFILE.zip_code=document.getElementById("zip_code").value;PROFILE.university=document.getElementById("university").value;PROFILE.uni_city=document.getElementById("uni_city").value;PROFILE.gpa=document.getElementById("gpa").value;PROFILE.degree=document.getElementById("selectdegree").value;PROFILE.major=document.getElementById("major").value;var e=document.getElementById("uni_start").value.split("-");
PROFILE.uni_start_month=parseInt(e[1]);PROFILE.uni_start_year=e[0];e=document.getElementById("grad_date").value.split("-");PROFILE.grad_month=parseInt(e[1]);PROFILE.grad_year=e[0];PROFILE.employer1=document.getElementById("employer1").value;PROFILE.job_title1=document.getElementById("job_title1").value;PROFILE.current_job1=document.getElementById("current_job1").checked;PROFILE.job_location1=document.getElementById("job_location1").value;e=document.getElementById("job_start1").value.split("-");PROFILE.job_start_month1=
parseInt(e[1]);PROFILE.job_start_year1=e[0];e=document.getElementById("job_end1").value.split("-");PROFILE.job_end_month1=parseInt(e[1]);PROFILE.job_end_year1=e[0];PROFILE.job_desc1=document.getElementById("job_desc1").value;PROFILE.employer2=document.getElementById("employer2").value;PROFILE.job_title2=document.getElementById("job_title2").value;PROFILE.current_job2=document.getElementById("current_job2").checked;PROFILE.job_location2=document.getElementById("job_location2").value;e=document.getElementById("job_start2").value.split("-");
PROFILE.job_start_month2=parseInt(e[1]);PROFILE.job_start_year2=e[0];e=document.getElementById("job_end2").value.split("-");PROFILE.job_end_month2=parseInt(e[1]);PROFILE.job_end_year2=e[0];PROFILE.job_desc2=document.getElementById("job_desc2").value;PROFILE.employer3=document.getElementById("employer3").value;PROFILE.job_title3=document.getElementById("job_title3").value;PROFILE.current_job3=document.getElementById("current_job3").checked;PROFILE.job_location3=document.getElementById("job_location3").value;
e=document.getElementById("job_start3").value.split("-");PROFILE.job_start_month3=parseInt(e[1]);PROFILE.job_start_year3=e[0];e=document.getElementById("job_end3").value.split("-");PROFILE.job_end_month3=parseInt(e[1]);PROFILE.job_end_year3=e[0];PROFILE.job_desc3=document.getElementById("job_desc3").value;PROFILE.username=document.getElementById("username").value;PROFILE.password=document.getElementById("password").value;PROFILE.question=document.getElementById("question").value;PROFILE.answer=document.getElementById("answer").value;
e=JSON.stringify(PROFILE);chrome.storage.local.set({profile:e},function(){chrome.storage.sync.set({profile:e},function(){document.getElementById("successMessage").style.visibility="visible";chrome.storage.local.get("profile",function(m){m.profile||console.error("Failed to save to local storage")});chrome.storage.sync.get("profile",function(m){m.profile||console.error("Failed to save to sync storage");m.profile&&(PROFILE=JSON.parse(m.profile))})})})}var l=document.getElementById("submit");let p=document.getElementById("profile");
FormPersistence.persist(p);l&&(l.onclick=function(){q()})});var _gaq=_gaq||[];(function(){})();
